### ISSUE TITLE
تداخل نوار عنوان فریم با زیربخش 

### ISSUE THREAD

**Issue by mojtabaahmadi2020tl** [kvafa/bidi#10]
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{beamer}
\usetheme{Warsaw}
\useoutertheme{tree} %smoothtree, smoothbars
\usepackage[RTLdocument]{bidi} 

\title{title}
\author{M.Ahmadi}
\begin{document}

\section{section}
\subsection{joy}
\begin{frame}{frametitle}
test
\end{frame}

\end{document}

## Expected behavior

درود جناب وفا، عنوان فریم به نظر میرسد که فاصله عمودی منفی دارد در فایل
 beamerouterthemeshadow-xetex-bidi.def

## Log and PDF files  

[test_Warsaw_tree.pdf](https://github.com/kvafa/bidi/files/8920199/test_Warsaw_tree.pdf)
[test_Warsaw_tree.log](https://github.com/kvafa/bidi/files/8920201/test_Warsaw_tree.log)

**Comment by kvafa** [comment]
Thanks for your bug report. Without using the `bidi` package, I get the same output which suggests that this is not the `bidi` package's issue. If there is any issue, it belongs to beamer.
