### ISSUE TITLE
psscalebox from pstricks does not work correctly when bidi loaded

### ISSUE THREAD

**Issue by bahman-mirzakhani** [kvafa/bidi#12]
## Brief outline of the issue
When I use `\psscalebox{<value>}{}` in presence of `bidi`, the output pdf is not valid!

In the log file I see this error:

> Error 35584 (driver return code) generating output;
file exam-LaTeX.pdf may not be valid.

## Check/indicate
- [ ] Relevant to the `xepersian` package
- [x] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [x] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}

\usepackage{pstricks}
\usepackage[RTLdocument]{bidi}

\begin{document}

	\psscalebox{1.2}{\pscircle{1.5}}

\end{document}
```

## Log and PDF files  
[exam-LaTeX.log](https://github.com/kvafa/bidi/files/9595174/exam-LaTeX.log)

**Comment by kvafa** [comment]
This is by design and not considered an issue/bug; see [here](https://qa.parsilatex.com/35720) for instance.
