### ISSUE TITLE
Spurious space after new commands footnotes

### ISSUE THREAD

**Issue by bahman-mirzakhani** [kvafa/bidi#18]
## Brief outline of the issue
Spurious space after new commands footnotes in text.

## Check/indicate
- [x] Relevant to the `xepersian` package
- [x] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [x] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass[12pt]{article}            % or some other class

\usepackage[%
	extrafootnotefeatures,%
]{xepersian}
\settextfont{IRXLotus}
\ParagraphFootnotes
\begin{document}
|\footnote{درود}|
\TwoColumnFootnotes
|\footnote{درود}|
\ThreeColumnFootnotes
|\footnote{درود}|
\FourColumnFootnotes
|\footnote{درود}|
\FiveColumnFootnotes
|\footnote{درود}|
\SixColumnFootnotes
|\footnote{درود}|
\SevenColumnFootnotes
|\footnote{درود}|
\NineColumnFootnotes
|\footnote{درود}|
\TenColumnFootnotes

\twocolumnfootnotes
|\footnote{درود}|

\end{document}
```

## Log and PDF files  
[test.pdf](https://github.com/kvafa/bidi/files/10468873/test.pdf)
[test.log](https://github.com/kvafa/bidi/files/10468874/test.log)

**Comment by kvafa** [comment]
Thanks for your bug report; please accept my apologies for the very late reply. I have resolved this in my own private repository (not publicly available). The new release will appear on CTAN at September 10, 2023 (about a month).

**Comment by bahman-mirzakhani** [comment]
Thanks a lot.
