### ISSUE TITLE
problem in tableofcontents, ball unnumbered

### ISSUE THREAD

**Issue by Tex-Ahmadi** [kvafa/bidi#19]
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass[10pt]{beamer}

\usepackage[RTLdocument=on]{bidi}

\setbeamertemplate{sections/subsections in toc}[ball unnumbered]

\begin{document}
\begin{frame}{contents}
\tableofcontents
\end{frame}

\section{test for title section}

\subsection{test for title subsection}
\begin{frame}{title}
test bidi version=\bidiversion
\end{frame}

\end{document}
```

## Expected behavior
**solve with add** in beamerbaseauxtemplates-xetex-bidi.def

```
\bidi@csundef{beamer@@tmpop@section in toc@ball unnumbered}

\bidi@csundef{beamer@@tmpop@subsection in toc@ball unnumbered}

\bidi@csundef{beamer@@tmpop@subsubsection in toc@ball unnumbered}

\defbeamertemplate{section in toc}{ball unnumbered}
{\leavevmode\bidi@beamer@leftskip=2.25ex%
  \llap{%
    \raise0.1ex\beamer@usesphere{section number projected}{bigsphere}\kern1.25ex}%
  \inserttocsection\par}

\defbeamertemplate{subsection in toc}{ball unnumbered}
{\leavevmode\bidi@beamer@leftskip=5.1ex\llap{%
    \raise0.2ex\beamer@usesphere{subsection number projected}{smallsphere}\kern1ex}\inserttocsubsection\par}

\defbeamertemplate{subsubsection in toc}{ball unnumbered}
{\leavevmode\normalsize\usebeamerfont{subsection in
    toc}\bidi@beamer@leftskip=8.2ex\usebeamerfont{subsubsection in toc}%
  \llap{%
    \beamer@usesphere{subsubsection number projected}{smallsphere}\kern0.75ex}\inserttocsubsubsection\par}
```

## Log and PDF files  

[beamer_toc_ball-unnumbered.pdf](https://github.com/kvafa/bidi/files/11071144/beamer_toc_ball-unnumbered.pdf)

**Comment by kvafa** [comment]
Thanks for your bug report; please accept my apologies for the very late reply. I have resolved this in my own private repository (not publicly available). The new release will appear on CTAN at September 10, 2023 (about a month).
