### ISSUE TITLE
Problem with long section title in table of contents, square 

### ISSUE THREAD

**Issue by Tex-Ahmadi** [kvafa/bidi#21]
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass[10pt]{beamer}

\usepackage[RTLdocument=on]{bidi}

\setbeamertemplate{sections/subsections in toc}[square]

\begin{document}
\begin{frame}{contents}
\tableofcontents
\end{frame}

\section{test for title section. This is a long text for testing. This is a long text for testing.}

\subsection{test for title subsection}
\begin{frame}{title}
test bidi version=\bidiversion
\end{frame}

\end{document}
```

## Expected behavior
**solve with edit**: beamerbaseauxtemplates-xetex-bidi.def

```
\defbeamertemplate{section in toc}{square}
{\leavevmode\bidi@beamer@leftskip=1.75ex%
  \llap{{%
    \usebeamerfont*{section number projected}%
    \usebeamercolor[bg]{section number projected}%
    \if@RTL
    \else
      \vrule width2.25ex height1.85ex depth.4ex%
      \hskip-2.25ex%
    \fi
    \hbox to2.25ex{{\hfil\color{fg}\inserttocsectionnumber\hfil}}%
    \if@RTL
      \hskip-2.25ex%
      \vrule width2.25ex height1.85ex depth.4ex%
    \fi
    }\kern1.25ex}%
  \inserttocsection\par}
```

## Log and PDF files  

[beamer_toc_square.pdf](https://github.com/kvafa/bidi/files/11071212/beamer_toc_square.pdf)

**Comment by kvafa** [comment]
Thanks for your bug report; please accept my apologies for the very late reply. I have resolved this in my own private repository (not publicly available). The new release will appear on CTAN at September 10, 2023 (about a month).
