### ISSUE TITLE
problem in caption name own line

### ISSUE THREAD

**Issue by Tex-Ahmadi** [kvafa/bidi#22]
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass[10pt]{beamer}

\usepackage[RTLdocument=on]{bidi}

\setbeamertemplate{caption}[caption name own line]

\begin{document}

\begin{frame}{caption name own line}
test bidi version=\bidiversion
\begin{table}
\caption{test title}
\begin{tabular}{cc}
1&2\\
3&4
\end{tabular}
\end{table}
\end{frame}

\end{document}
```

## Expected behavior
**solve with add beamerbaseauxtemplates-xetex-bidi.def**

```
\bidi@csundef{beamer@@tmpop@caption@caption name own line}

\defbeamertemplate{caption}{caption name own line}
{%
  \begin{minipage}{\textwidth}
    \bidi@beamer@ragged%
  {\leavevmode%
    \usebeamercolor[fg]{caption name}%
    \usebeamerfont*{caption name}%
    \insertcaptionname%
    }\\
      \insertcaption
    \end{minipage}
}
```

## Log and PDF files  

[bidi-caption-beamer.pdf](https://github.com/kvafa/bidi/files/11071217/bidi-caption-beamer.pdf)

**Comment by kvafa** [comment]
Thanks for your bug report; please accept my apologies for the very late reply. I have resolved this in my own private repository (not publicly available). The new release will appear on CTAN at September 10, 2023 (about a month).
