### ISSUE TITLE
problem place navigation symbols for plain frame

### ISSUE THREAD

**Issue by Tex-Ahmadi** [kvafa/bidi#24]
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{beamer}

\usetheme{PaloAlto}

\usepackage[RTLdocument=on]{bidi}

\title{test}
\author{m.ahmadi}

\begin{document}

\begin{frame}[plain]
test bidi version=\bidiversion

probleam place navigation symbols for plain frame
\end{frame}

\end{document}
```

## Log and PDF files  

[place-navigation-plain-bidi.pdf](https://github.com/kvafa/bidi/files/11071226/place-navigation-plain-bidi.pdf)

**Comment by kvafa** [comment]
Thanks for your bug report; please accept my apologies for the very late reply. I have resolved this in my own private repository (not publicly available). The new release will appear on CTAN at September 10, 2023 (about a month).
