### ISSUE TITLE
Page numbering alignment in ToC, LoF, and LoT in presence of bidi and tocloft

### ISSUE THREAD

**Issue by bahman-mirzakhani** [kvafa/bidi#26]
## Brief outline of the issue
When I use tocloft package with bidi package, page numbers are not left alignment in ToC, LoF, and LoT.

## Check/indicate
- [ ] Relevant to the `xepersian` package
- [x] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}
\usepackage{showframe}
\usepackage{tocloft}
\usepackage[%
	RTLdocument%
]{bidi}
\begin{document}

	\tableofcontents
	\listoffigures
	\listoftables

	\section{Test}
	\subsection{Other}
	\subsection{Other}
	
	\begin{figure}[!htb]
		\caption{Test}
	\end{figure}
	\begin{table}[!htb]
		\caption{Test}
	\end{table}

\end{document}
```

## Log and PDF files  
[test.pdf](https://github.com/kvafa/bidi/files/11072090/test.pdf)
[test.log](https://github.com/kvafa/bidi/files/11072091/test.log)

**Comment by kvafa** [comment]
Thanks for your bug report; please accept my apologies for the very late reply. I have resolved this in my own private repository (not publicly available). The new release will appear on CTAN at September 10, 2023 (about a month).

**Comment by bahman-mirzakhani** [comment]
Thanks a lot.
