### ISSUE TITLE
Large banner in output is inappropriate

### ISSUE THREAD

**Issue by eyalroz** [kvafa/bidi#32]
Whenever I use the `bidi.sty` package/style file, I get a long banner (25 lines!) introducing it. This boilerplate is:

* Not useful to the user compiling a document (they know that each style file has a self-describing comment, plus there is CTAN documentation for packages, search engines etc.)
* Contradicts the custom for (La)TeX packages
* Clutters the log and hides meaningful messages

Please remove it entirely, or at the very list - limit yourself to a single package-describing line.

## Check/indicate
- [ ] Relevant to the `xepersian` package
- [X] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}            % or some other class

  % Any packages other than the bidi package must be loaded here

  % The bidi package must be loaded as the last package
\usepackage[%
    % Any bidi package option goes here
]{bidi}

  % Any preamble code goes here
  
\begin{document}

Hello world
  
\end{document}
```

## Expected behavior

Log should say:
```
(/usr/share/texlive/texmf-dist/tex/xelatex/bidi/bidi.sty)
```
and that's it.

## Log and PDF files  

Relevant part:
```
(/usr/share/texlive/texmf-dist/tex/xelatex/bidi/bidi.sty
****************************************************
* 
* bidi package (Bidirectional typesetting in
* plain TeX and LaTeX, using XeTeX engine)
* 
* Description: A convenient interface for
* typesetting bidirectional texts in plain TeX
* and LaTeX. The package includes adaptations
* for use with many other commonly-used packages.
* 
* Copyright (c) 2007--2023 Vafa Khalighi
* Copyright (c) 2018--2020 bidi-tex GitHub organization
* 
* v39.7 (Release Serge Lang), 2023/01/18
* 
* License: LaTeX Project Public License, version
* 1.3c or higher (your choice)
* 
* Location on CTAN: /macros/xetex/latex/bidi
* 
* Issue tracker: https://github.com/kvafa/bidi/issues
* 
* Discussions: https://github.com/kvafa/bidi/discussions
* 
* Primary author of bidi package: Vafa Khalighi.
* 
****************************************************
```

**Comment by Udi-Fogiel** [comment]
Until it will be fixed, you can do the following workaround
```TeX
\documentclass{article} 
\let\origtypeout\typeout
\def\typeout#1{\let\typeout\origtypeout}
\usepackage{bidi}
\begin{document}
	
	Hello world

\end{document}
```

**Comment by eyalroz** [comment]
> You might also want to disable the bidi's enddocument hook as the release information is for some reason cluttering the pdf custom properties

This is interesting, but is a matter for another bug report. Can you please file it and explain what exactly is being cluttered and what the result is?

**Comment by eyalroz** [comment]
> Until it will be fixed, you can do the following workaround

I might do that in my own document, but I'm a document class author, and it's probably better for me to avoid such tricks.

**Comment by Udi-Fogiel** [comment]
> This is interesting, but is a matter for another bug report. Can you please file it and explain what exactly is being cluttered and what the result is?

I'm not sure this is a bug, it looks intentional. At the bottom of `bidi.sty` you can find
```TeX
\AtEndDocument{%
   \special{pdf:%
     docinfo<<%
     \if@bidi@pdfm@mark
       /Creator(\@bidi@pdfcreator)%
       /Producer(\@bidi@pdfproducer)%
     \fi
     /BIDI.Fullbanner(\@bidi@pdfcustomproperties)%
     \if@bidi@csdef{@xepersian@pdfcustomproperties}{%
       /XEPERSIAN.Fullbanner(\@xepersian@pdfcustomproperties)%
     }{}%
      >>%
    }%
}
```

`\if@bidi@pdfm@mark` is false by default, so the Creator and Producer fields isn't affected. On the other hand,  the field `BIDI.Fullbanner` is created with the release information. You can see it for example with acrobat reader in `Menu->Document Properties->Custom`. Or with the following code that produce uncompressed pdf file 
```TeX
\special{dvipdfmx:config z 0}
\documentclass{article}
\usepackage{bidi}
\begin{document}	
	Hello world	
\end{document}
```
you will find the line 
`/BIDI.Fullbanner(This is the bidi package, Version 39.8 \(Release Donald Ervin Knuth\), Released August 2, 2023. )`
in the docinfo dictionary (next to `/Creator`, `/Producer` etc. ).

> I might do that in my own document, but I'm a document class author, and it's probably better for me to avoid such tricks.
Yes, this is indeed a dirty hack, but I've seen worse. You can always add support for `LuaTeX` in your document class, using `babel` or `polyglossia` + `luabidi`.  I don't think these kind of problems exists there.

**Comment by Udi-Fogiel** [comment]
In any case this has been like that (sometimes worse) for many years, and I wouldn't hold my breath until it will be fixed (if at all). 
See

* https://github.com/kvafa/bidi/issues/16

* https://tex.stackexchange.com/questions/411907/suppress-bidis-logo-when-using-polyglossia

for more examples of similar problems. These ones actually made/makes the package unusable without hacks.

**Comment by kvafa** [comment]
@eyalroz Thanks for your bug report. This is for historical reasons and it has existed for many years. Although I can not remove it entirely, I am happy to add an option to disable it. If you are happy with this, please let me know. I am quite occupied by other commitment and I'm afraid the new versions will not appear on CTAN anytime soon.

@Udi-Fogiel You are giving false information by mixing things. I am not sure what is your agenda and what you are trying to achieve but whatever it is you are not doing anything constructive.

The options logo and pdfinfo when they were introduced, were on by default and the polyglossia issue you are referring to is about the option logo. David Carlisle asked me to make it off by default and I exactly did this when it was introduced.In other words, this issue does not exist for many years.

The other issue you are referring to is a technical issue which needs to be fixed and it is unrelated to the rest of your false claims. I just have not had enough time to look into my TeX packages recently as I am occupied by other commitments but as soon as I can find some free time, I will look into it.

The custom properties have existed for many years. No one has ever complained about them as far as I know and it is a feature not a bug.

**Comment by Udi-Fogiel** [comment]
> @Udi-Fogiel You are giving false information by mixing things. I am not sure what is your agenda and what you are trying to achieve but whatever it is you are not doing anything constructive.

@kvafa My only  agenda was to help Eyal. I sincerely apologize if I offended you in any way. The only reason I mentioned the Fullbanner information is because I know that Eyal is maintaining a documentclass for students to write their thesis in, and I remembered my university wasn't happy with that feature. 

I wasn't trying to imply this subject, or the logo option were closely related to the information written to the log.  I just referenced them as they are similar, in the manner that they are all, in some way or another, print the credits of the package. 

I'm not sure what false information, or false claims I gave. I would appreciate if you can elaborate more so I won't repeat my mistakes. 

>and the polyglossia issue you are referring to is about the option logo

The `pdfinfo` option is briefly mentioned there as well, in the comments. 

> The custom properties have existed for many years. No one has ever complained about them as far as I know and it is a feature not a bug.

By "custom properties" are you referring to the package options? If so, Bidi.Fullbanner is not part of them.

**Comment by eyalroz** [comment]
@kvafa : An option to disable it would be nice, although we'd need to get it pushed into polyglossia, which is where the bidi package is often used. I don't mind if it'll take a while - after all, this isn't a bug, it's just an annoyance. However - I do think it would be better if no-large-banner would be the default rather than something one opts into; I think that makes more sense.

@Udi-Fogiel , @kvafa : Let us please move all of this discussion of what happens at the end of a document to a separate issue, since it really does not belong on this one. Kindly suggest that the comments about it be removed and made again (perhaps in summary) on a new issue page.

**Comment by Udi-Fogiel** [comment]
> @Udi-Fogiel , @kvafa : Let us please move all of this discussion of what happens at the end of a document to a separate issue, since it really does not belong on this one. Kindly suggest that the comments about it be removed and made again (perhaps in summary) on a new issue page.

Done at #33

**Comment by ghost** [comment]
I have uploaded version `40.3` of the `bidi` package to CTAN just now where it introduces a new package option `banner` with two values `on` (default) and `off`.  If you do not want to see `bidi` banner in log and terminal, then simply load the `bidi` package via

```tex
\usepackage[%
  banner=off%
]{bidi}
```
If this addresses your issue, then please consider closing this issue.

Please also note that this repository is unmaintained. The `bidi` package has a [new repository](https://github.com/xepersian/bidi).

**Comment by eyalroz** [comment]
So, closing, but I still think banner-off should be the default.

**Comment by ghost** [comment]
Thanks for your reply. If this banner was new, I would be more than happy to make it off by default but it has existed for more than 10+ years and if I were to make it off by default, then it would be a sudden behavior change and sort of backward incompatible.
