### ISSUE TITLE
disable bidi's custom pdf properties 

### ISSUE THREAD

**Issue by Udi-Fogiel** [kvafa/bidi#33]
## Check/indicate
- [ ] Relevant to the `xepersian` package
-  [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode

\documentclass{article}      
\usepackage{bidi}
  
\begin{document}
  Hello!
\end{document}
```

## Problem 
The pdf and xdv produced by the minimal example contains in it the line 
BIDI.Fullbanner(This is the bidi package, Version 39.8 (Release Donald Ervin Knuth) Released August 2, 2023. ), 
(it is inserted to the pdf via the `docinfo` key).  It can create problems if the the establishment to whom the pdf is created
does not accept it because of that fact. It would nice to have an appropriate way to disable that. 

Today, thanks to LaTeX's new hook management system  one can remove with 
```TeX
\documentclass{article}      
\usepackage{bidi}
 \RemoveFromHook{enddocument}[bidi]
\begin{document}
  Hello!
\end{document}
```

But that removes bidi's enddocument hook entirely, which might be undesirable.

**Comment by ghost** [comment]
I have uploaded version `40.3` of the `bidi` package to CTAN just now where it introduces a new package option `PDFbanner` with two values `on` (default) and `off`.  If you do not want to see `bidi` banner in custom PDF property, then simply load the `bidi` package via

```tex
\usepackage[%
  PDFbanner=off%
]{bidi}
```
If this addresses your issue, then please consider closing this issue.

Please also note that this repository is unmaintained. The `bidi` package has a [new repository](https://github.com/xepersian/bidi).

**Comment by Udi-Fogiel** [comment]
Thanks for all your work on recent versions of bidi!

**Comment by ghost** [comment]
Thanks a lot for your various bug reports and I am sorry that it took me too long. From memory, I think you also asked for LuaTeX support for `bidi` package but I do not seem to be able to find where. I have tested LuaTeX and `bidi` since day one it existed. It is should not be too hard to add support for LuaTeX. The first step is to implement unicode bidirectional algorithm. 

Having said that, I think LuaMetaTeX is the future. It is a matter of time when LuaTeX becomes obsolete.
