### ISSUE TITLE
unnumbered part in article is not correctly aligned. 

### ISSUE THREAD

**Issue by Udi-Fogiel** [kvafa/bidi#35]
## Check/indicate
- [ ] Relevant to the `xepersian` package
-  [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode
\documentclass{article}
\usepackage[RTLdocument]{bidi}
\begin{document}
\part{Test}
\part*{Test}
\end{document}
```

## Expected behavior

Both titles should be aligned the same.

Should be fixed by #28

**Comment by ghost** [comment]
I have fixed this in version `40.1` of the `bidi` package and uploaded it about a week ago. It should already be available on TeXLive via update.

If this addresses your issue, then please consider closing this issue.

Please also note that this repository is unmaintained. The `bidi` package has a [new repository](https://github.com/xepersian/bidi).
