### ISSUE TITLE
\XeTeX and \XeLaTeX "already defined"

### ISSUE THREAD

**Issue by wujastyk** [kvafa/bidi#39]
## Brief outline of the issue

Lines 140-144 of `latex-xetex-bibdi.def` 
```
%\bidi@newrobustcmd*{\XeTeX}{\LR{\leavevmode$\smash{\hbox{X\lower.5ex
%  \hbox{\kern-.125em\bidi@reflect@box{E}}\kern-.1667em \TeX}}$}}
%\bidi@newrobustcmd*{\XeLaTeX}{\LR{\leavevmode$\smash{\hbox{X\lower.5ex
%  \hbox{\kern-.125em\bidi@reflect@box{E}}\kern-.1667em \LaTeX}}$}}

```
are causing an error message for me of the type, 
```
[\XeTeX | \XeLaTeX ] already defined 
```
I have a multilingual document using a special journal style and class that's pretty stable ([HSSA](https://github.com/wujastyk/HSSA)), so it's hard for me to give an MWE.   I've eliminated the [obvious things](https://tex.stackexchange.com/questions/374454/error-related-to-bidi-or-arabxetex-command-xetex-already-defined): xltextra, fontspec.  I'm not using arabtex.  I am using polyglossia with other languages (greek, sanskrit, chinese).  This issue arises when I add 
```
\setotherlanguage{persian}
\newfontfamily\persianfont{Noto Sans Arabic}
```

## Check/indicate
- [ ] Relevant to the `xepersian` package
- [ x] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [x ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode

\documentclass{hssa}
\usepackage{hssa}
%
\setotherlanguage{persian}  % this line alone produces the error message
%\newfontfamily\persianfont{Noto Sans Arabic}

\begin{document}
Hello world!
\end{document}
```

## Log and PDF files  

[sarma-kkk.log](https://github.com/kvafa/bidi/files/13708930/sarma-kkk.log)
[sarma-kkk.pdf](https://github.com/kvafa/bidi/files/13708931/sarma-kkk.pdf)

**Comment by ghost** [comment]
I have fixed this in version `40.1` of the `bidi` package and uploaded it about a week ago. It should already be available on TeXLive via update.

If this addresses your issue, then please consider closing this issue.

Please also note that this repository is unmaintained. The `bidi` package has a [new repository](https://github.com/xepersian/bidi).
