### ISSUE TITLE
Lineno render incorrectly with bidi 

### ISSUE THREAD

**Issue by seloumi** [kvafa/bidi#40]
## Brief outline of the issue

Adding `bidi`  package to 2-column paper with line numbers on the sides using the lineno package with   `switch` option produce line number to appears on the left side of the right column.

https://tex.stackexchange.com/q/712502/54817
 
## Check/indicate
- [ ] Relevant to the `xepersian` package
- [x] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [x] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode
\documentclass[11pt,twocolumn]{article}

\usepackage[switch,mathlines]{lineno}

\usepackage{bidi}
\usepackage{lipsum}

\linenumbers

\begin{document}
\lipsum
\end{document}
```

## Expected behavior

![image](https://github.com/kvafa/bidi/assets/8249073/fefcfd6f-9851-4c0e-949d-31d40e2d271c)

## Log and PDF files  

[test5.pdf](https://github.com/kvafa/bidi/files/14559985/test5.pdf)
[test5.log](https://github.com/kvafa/bidi/files/14559986/test5.log)

**Comment by ghost** [comment]
I have fixed this in version `40.1` of the `bidi` package and uploaded it about a week ago. It should already be available on TeXLive via update.

If this addresses your issue, then please consider closing this issue.

Please also note that this repository is unmaintained. The `bidi` package has a [new repository](https://github.com/xepersian/bidi).
