### ISSUE TITLE
bidi causes duplicated @-expressions in longtable

### ISSUE THREAD

**Issue by logological** [kvafa/bidi#41]
## Brief outline of the issue

With a recent (2024-06-01-ish) release of LaTeX, use of the `bidi` package in conjunction with the `memoir` class causes the @-expressions of `longtable` environments to be printed extraneously.  It seems that using a `\multicolumn` command is necessary to trigger the bug.

According to the discussion at Issue latex3/latex2e#1368, this may be because the `array` package, whose definitions `bidi` redefines, was recently changed.

I can reproduce the problem only with `memoir`; the standard `article` and `book` classes seem to be unaffected.

## Check/indicate
- [ ] Relevant to the `xepersian` package
- [x] [The `bidi` package issue tracker](https://github.com/kvafa/bidi/issues) has been searched for similar issues?
- [x] [The `xepersian` package issue tracker](https://github.com/kvafa/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
\documentclass{memoir}
\usepackage{longtable}
\usepackage{bidi}
\begin{document}

\begin{longtable}{l}
\multicolumn{1}{c}{foo} \\
\end{longtable}

\begin{longtable}{r@{x}l@{x}r@{x}l@{x}r@{x}l}
a & b & c & d & e & f \\
\end{longtable}
\end{document}
```

## Expected behavior

The second `longtable` environment should print something like the following:

> `axbxcxdxexf`

Instead it prints the following:

> `axbxcxdxexf`
> ` x`

## Log and PDF files  

[test.log](https://github.com/user-attachments/files/15744739/test.log)
[test.pdf](https://github.com/user-attachments/files/15744740/test.pdf)

**Comment by logological** [comment]
I've reported the problem to the `memoir` class maintainer.  They responded that it's not a `memoir` problem but rather an interaction between `bidi` and `array` (the latter of which `memoir` preloads, but the standard `article` class does not). So here's an alternative minimal example that uses `article`:

```tex
\documentclass{article}
\usepackage{array}
\usepackage{longtable}
\usepackage{bidi}

\begin{document}
\begin{longtable}{l}
\multicolumn{1}{c}{foo} \\
\end{longtable}

\begin{longtable}{r@{x}l@{x}r@{x}l@{x}r@{x}l}
a & b & c & d & e & f \\
\end{longtable}
\end{document}
```
[test.pdf](https://github.com/user-attachments/files/15806597/test.pdf)
[test.log](https://github.com/user-attachments/files/15806598/test.log)

**Comment by logological** [comment]
With the latest release of `array` (2.6d on 2024-06-14) the problem is no longer reproducible.  However, the discussion in latex3/latex2e#1368 suggests that the root of the problem is `bidi`'s redefinition of internal things from `array`, and so it might be better if `bidi` were eventually updated to play nice with the new definitions.

**Comment by ghost** [comment]
I have fixed this in version `40.1` of the `bidi` package and uploaded it about a week ago. It should already be available on TeXLive via update.

If this addresses your issue, then please consider closing this issue.

Please also note that this repository is unmaintained. The `bidi` package has a [new repository](https://github.com/xepersian/bidi).

**Comment by logological** [comment]
@vkhalighi Thanks; I'll test soon.  What happened to this repository and your old GitHub account?

**Comment by ghost** [comment]
Thanks. I no longer have access to the email address registered with my old GitHub account. Whenever I try to login, GitHub sends a code to my old email address and as a result, I can not log in. I asked GitHub customer service and was told that there is nothing that can be done and I should create a new GitHub account instead.

**Comment by logological** [comment]
Confirmed issue is no longer reproducible with bidi v40.4 (Release John Willard Milnor), 2024/12/15
